GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json 

{
    "name": "Dia1",
    "password": "12364"
}

###

POST http://localhost:3000/login
Content-Type: application/json 

{
    "name": "Dia1",
    "password": "12364"
}

###

GET http://localhost:3000/api

